package academy.pocu.comp2500.assignment1;

public enum ESortWay {
    WRITE_TIME_DESCENDING,
    WRITE_TIME_ASCENDING,
    ADJUST_TIME_DESCENDING,
    ADJUST_TIME_ASCENDING,
    TITLE_DICTIONARY_ASCENDING
}